### ISSUE TITLE
Invisible underscores, call stack

### ISSUE THREAD

**Issue by darvelo** [s10wen/SO-Dark-Monokai-v3#11]
Hey, I haven't seen any search results on this so I'm wondering if it's just me.. I can't see underscores or odd-numbered functions in the call stack.

![underscore](https://f.cloud.github.com/assets/523169/405643/39f8a6b8-a9f9-11e2-96ce-4190635dac79.png)

![callstack](https://f.cloud.github.com/assets/523169/405644/3f3232a2-a9f9-11e2-83b0-934d37201639.png)

I selected that second-to-last function so you could see what I mean.. Is there anything I can do about this? Makes coding kinda like a hide-and-seek.  :)

**Comment by darvelo** [comment]
Oh, sorry, I pulled from master and the call stack issue was fixed. The underscore thing still happens though.

**Comment by s10wen** [comment]
There's some info [here](http://simonowendesign.co.uk/blog/2012/11/04/styling-the-chrome-dev-tools/) on how to update the theme, if you could have a look at that, amend the CSS, then send over a pull request that be awesome, if you get stuck let me know and I'll have a look.

**Comment by darvelo** [comment]
Okay, looks like it's fixed. Webkit inspector says devTools.css is overriding the user styles, but clearly they're applied. Thanks for showing me how to do this! If you teach a man to fish... well, you know the rest.

**Comment by s10wen** [comment]
Indeed! See half way through these slides: http://www.rvl.io/simonowendesign/mcrfred-1#/

Will check out the PR soon.

**Comment by darvelo** [comment]
Hahaha, yes! Epic slide. I think I've found my new mantra. :D

Also, I really like what you're doing with FRED. Kudos, Simon.
