### ISSUE TITLE
Current Debug Line Color

### ISSUE THREAD

**Issue by bazjapan** [s10wen/SO-Dark-Monokai-v3#13]
Hi again, hope you are well.
I have another area I'd like to change the color of.
When debugging the selected line color makes the underlying text difficult.

![image](https://f.cloud.github.com/assets/108936/451919/25361cca-b2c2-11e2-9a73-97dfb154dcff.png)

I'd have no background color and just have a strong border color.

Finding the classes is really difficult, it would be nice if we could inspect the inspector ;)
Anyways, not really an issue but I thought I'd bring it to your attention.
cheers

**Comment by s10wen** [comment]
Hey, yeah that sucks, I'll have a look.

You can [inspect the inspector](http://simonowendesign.co.uk/blog/2012/11/04/styling-the-chrome-dev-tools/) to a certain degree, but it would be nice to be able to 'Inspect Element' from the Chrome Dev Tools. Any chance that is possible @paulirish ?

Also, I'd recommend checking out:
https://github.com/mauricecruz/chrome-devtools-zerodarkmatrix-theme/

He's been fairly active and fixing things.

**Comment by bazjapan** [comment]
Thanks for that. He has certainly put a funky bit of styling together there.

**Comment by s10wen** [comment]
Yo @mauricecruz can I get a bit of advice on this please? Do you know of a global class that's for highlighted code, or do you tend to do on a per case basis?

**Comment by mauricecruz** [comment]
If I think I understand what you're talking about... this should cover it:

```
#-webkit-web-inspector .CodeMirror .CodeMirror-selected,
#-webkit-web-inspector ::selection {
    background: #<color> !important;
}
```

**Comment by s10wen** [comment]
Ta, that solved one of the issues, what about the code for 'Edit as HTML' please?

I get this and when I go to inspect the inspector it vanishes so having trouble grabbing the class name.
![screen shot 2013-10-18 at 10 55 35](https://f.cloud.github.com/assets/1136114/1359358/765e30ee-37db-11e3-898d-594da84ea4e9.png)

Yours looks sweet :smile_cat:
![screen shot 2013-10-18 at 10 53 19](https://f.cloud.github.com/assets/1136114/1359347/3cc1e20e-37db-11e3-87b9-b3620c9fee50.png)

**Comment by mauricecruz** [comment]
I'm pretty sure the 'Edit as HTML' picks up the styles set by Codemirror.  It's in my Code Highlighting section.  

You can prevent the view from vanishing by setting a 'break on subtree modification' breakpoint on the parent container where the edit module generates.  Then just keep stepping through until the text generates.

**Comment by mauricecruz** [comment]
fyi..looks like you have the wrong css loaded from my repo.  I had a typo in the curl scripts which caused the wrong one to load.  The border should be a little more pleasant looking :smile: 

![image](https://f.cloud.github.com/assets/1640686/1362411/4401d5ae-3819-11e3-9d5e-3e95889c5fc1.png)

**Comment by paulirish** [comment]
Unrelated, but you guys may have noticed... 

The id of the devtools has now changed and that'll probably break 100% of themes.

```
<body class="undocked" id="-blink-dev-tools">
```

We broke it because the UI is going to change a bit.

**Comment by s10wen** [comment]
@mauricecruz 'break on subtree modification' - having trouble doing this, please can you tell me the steps to do this / do a screencast?

'like you have the wrong css' - I'm not to keen on the drop shadow bit, but yeah the 1px border could do with some love :)

@paulirish thanks for the heads up, will keep a look out.

**Comment by mauricecruz** [comment]
@paulirish Thanks for the info.  There's a handful of breaking changes in the latest canary :grimacing:.  Womp womp.  

@simonowendesign I'll document some instructions.

**Comment by RaphaelDDL** [comment]
Just as info I just discovered, Google removed the custom stylesheet from Canary (which probably will reflect on stable when it gets to v32~v33)...

I was reporting the problem on an undock bug at [code.google](https://code.google.com/p/chromium/issues/detail?id=317445#c14) and learned of that..
-> https://codereview.chromium.org/66383005/ 

I noted last week but I though my custom was just wrong since I was messing with it..

Bad move, Google.
R.i.p. custom.css

**Comment by s10wen** [comment]
:worried: W00t... :worried: Will investigate...

**Comment by s10wen** [comment]
I'm moving this theme over to https://github.com/mauricecruz/zero-base-themes/
