### ISSUE TITLE
No closing (x) icon to exit inspector

### ISSUE THREAD

**Issue by dentz** [s10wen/SO-Dark-Monokai-v3#14]
There is no close button visible on the top bar as shown in the screenshots.

Chrome version: 26.0.1410.65

http://imgur.com/WhqhA13.png

**Comment by s10wen** [comment]
Yeah, noticed this had vanished, personally I don't mind it not being there and use the shortcut: ⌘⌥I

**Comment by dentz** [comment]
I'm using the shortcut also, just need to get back into the habit as I was using the (x) on my previous theme. Thanks

**Comment by s10wen** [comment]
Going to close this, as it's not required.
