### ISSUE TITLE
Chrome v28 issues

### ISSUE THREAD

**Issue by RaphaelDDL** [s10wen/SO-Dark-Monokai-v3#16]
Hello there,

The theme was awesome on my Chrome until version `27.XX`

Today updated to version `28.0.1500.52 m` (damn auto update) and various issues showed up:
- The tabs are no longer on different places (console as first, etc) [See Image 1];
- The `+` and `-` on ALL inspector tabs are misplaced [See Image 1];
- `Event Listeners` menu is broken (both on alignment and showing broken images) when opening it for the first time (closing the down arrow and reopening "fixes", except the images) [See Image 1];
- All right windows (like HTML and Sources) where has lists had the `+` (or arrow, don't remember) became a black square with white border [See Image 2 and 3];
- The `Event Listener Breakpoints` (and probably others) had their font color messed (had to select text to read) [See Image 3];
- The `Headers` on `Network` tab have black font color for values, barely readable [See Image 4].

Image 1
![chrome28-1](https://f.cloud.github.com/assets/1087109/698662/fd7b2878-dd15-11e2-8d32-80b4bac52baa.png)

Image 2
![chrome28-2](https://f.cloud.github.com/assets/1087109/698663/fd840ad8-dd15-11e2-8aed-1dc42de58ae8.png)

Image 3
![chrome28-3](https://f.cloud.github.com/assets/1087109/698665/fda1200a-dd15-11e2-9d4b-bee2dda5dbe4.png)

Image 4
![chrome28-4](https://f.cloud.github.com/assets/1087109/698666/fda9f0d6-dd15-11e2-81b3-6e8097d1c28d.png)

It seems Chrome version 28 came to destroy the current theming :(
I tried apply the current theme .css again thinking was some .css file bug but seems it's the browser update.

Thanks for your time.

Best Regards,
RaphaelDDL

**Comment by s10wen** [comment]
Thanks for the heads up, will look into it when I get a min.

**Comment by s10wen** [comment]
Some of these issues were the same in stable Chrome 27.0.1453.116.

Have fixed them in stable https://github.com/simonowendesign/SO-Dark-Monokai-v3/commit/68994c2e734fcecd4530cf6c6f4c6e10c3243563, going to look at creating a separate css file for Canary.

**Comment by RaphaelDDL** [comment]
Yeah, I think the black values on `headers` and the event listener font colors were on v27 also. But since v28 made more bugs, I just reported all of them at once now.

By the way, thanks for your time looking on the issue.

**Comment by s10wen** [comment]
Think I've got these if you could check over please, I've added another file specifically for Canary:
https://github.com/simonowendesign/SO-Dark-Monokai-v3/blob/master/Canary/Custom.css

**Comment by s10wen** [comment]
Arrows fixed:
![screen shot 2013-06-25 at 21 53 10](https://f.cloud.github.com/assets/1136114/705861/9049a1ac-ddde-11e2-92cf-e4b8e9a1df51.png)

Console as first tab:
![screen shot 2013-06-25 at 22 03 28](https://f.cloud.github.com/assets/1136114/705866/a324e4da-ddde-11e2-964c-4b7c1e9c7ab7.png)

Sources > Event Listener Breakpoints arrows fixed and text colour:
![screen shot 2013-06-25 at 22 22 29](https://f.cloud.github.com/assets/1136114/705875/bbba0c82-ddde-11e2-9855-dd1be2c64580.png)

Network > Headers now readable:
![screen shot 2013-06-25 at 22 33 17](https://f.cloud.github.com/assets/1136114/705886/f15e16ee-ddde-11e2-9ada-f3cefc4fff52.png)

Tested in: Version 29.0.1546.0 canary

**Comment by RaphaelDDL** [comment]
All your screens and fixes confirmed on Chrome v28 @ Win7. :+1: 

The only difference is the text alignment of tabs (on bottom), probably Windows' fault, nothing to worry about.

Thanks for your work, that was awesome! I just love this theme <3

**Comment by s10wen** [comment]
Cool, ta :v:

**Comment by RaphaelDDL** [comment]
@simonowendesign Seems Google Chrome Team don't like themes. v30 onwards (chrome beta channel and canary) again broke all theme.

Sad :/

**Comment by s10wen** [comment]
Before:
![screen shot 2013-08-23 at 14 15 41](https://f.cloud.github.com/assets/1136114/1016288/5a7d2bc0-0bf6-11e3-84c5-c4ed6f3013b2.png)

After:
![screen shot 2013-08-23 at 14 15 51](https://f.cloud.github.com/assets/1136114/1016289/5f77e944-0bf6-11e3-9c69-312904281445.png)

Tested in: 31.0.1609.0 canary

Was there anything else you noticed?

**Comment by RaphaelDDL** [comment]
Okay, 'all' was too harsh. Sorry. :(

Yeah, that you showed and these:
![image](https://f.cloud.github.com/assets/1087109/1016353/0796056a-0bf8-11e3-8379-61364e3e1eb1.png)
![image](https://f.cloud.github.com/assets/1087109/1016385/b7e5ecc8-0bf8-11e3-8272-37f0ac7ada11.png)

I can't remember if the text after `Timer Fired` was already unreadable as is now. (I don't use that part anyways - just memory graph- just saying).
![image](https://f.cloud.github.com/assets/1087109/1016370/88bb6f04-0bf8-11e3-9d33-65a4675c1062.png)

**Comment by s10wen** [comment]
Zomg, they've moved them to tabs! Hmm, not sure about that move. Will have a look at this, yeah the whole Timeline needs looking at tbh.

**Comment by RaphaelDDL** [comment]
I actually liked the tabs, less `>` to be opened and stacked (and so, less vertical scrolls). I'll try check here also, but I get a bit confused with all those crazy class names :D
Other thing they implemented on devtools since v29 is the sass sourcemaps, lot easier to debug now =D

By the way, intended or not but closing X is back =)

**Comment by s10wen** [comment]
I did see the closing X briefly, but then it went again. Made some updates recently:

https://github.com/simonowendesign/SO-Dark-Monokai-v3/commit/88d89e8f80df80c64b04aa7caee7d850ae9f262a
https://github.com/simonowendesign/SO-Dark-Monokai-v3/commit/dc31c7e278b5b8bc786b3fb865e1083a248cccb2

if you could check over and let me know.

**Comment by RaphaelDDL** [comment]
The changes I noticed:

Tabs from:
![image](https://f.cloud.github.com/assets/1087109/1057547/5ead067c-1176-11e3-854b-8e2b73421f92.png)

To:
![image](https://f.cloud.github.com/assets/1087109/1057544/4c92cae4-1176-11e3-8355-c6691062bf77.png)

The tab changes affected the network tabs also (just bg color):
![image](https://f.cloud.github.com/assets/1087109/1057561/adb54de2-1176-11e3-937f-bad3e0769d25.png)

And have affected settings also:
![image](https://f.cloud.github.com/assets/1087109/1057583/5abefa38-1177-11e3-9584-7a8e236da9e9.png)

Preview/Response - gray on white. Probl lost black bg:
![image](https://f.cloud.github.com/assets/1087109/1057607/e03e1d1a-1177-11e3-8eaf-99e70c66457e.png)

I know google chrome team is always trying to improve but messing with devtools css every new version seems very annoying to maintain a theme. Is there a place you check the new classes and id's or you simply inspect the inspector? i wanna try help ya to easy the burden of all the changes.

**Comment by s10wen** [comment]
Thanks for this, will have a look. Yeah it's been mentioned: https://twitter.com/paul_irish/status/372967187285176321

Are you familiar with the Cmd + Shift + C shortcut in dev tools to help inspect the element?

**Comment by RaphaelDDL** [comment]
> Are you familiar with the Cmd + Shift + C shortcut in dev tools to help inspect the element?

You mean the shortcut for the inspector (looking glass icon)? Yup.

**Comment by s10wen** [comment]
Yeah, that's the one. If you have 2x CDT up, then using that makes it easier to find the class name you're after.

**Comment by RaphaelDDL** [comment]
Found out how inspect the inspector:

http://stackoverflow.com/questions/12291138/how-do-you-inspect-the-web-inspector-in-chrome

Will try style the Settings window and let you know :D
