### ISSUE TITLE
Console arrows are black

### ISSUE THREAD

**Issue by max-degterev** [s10wen/SO-Dark-Monokai-v3#19]
![screen shot 2013-08-29 at 11 28 14 am](https://f.cloud.github.com/assets/789031/1048504/5be6241c-108d-11e3-82a7-cba6241cd36d.png)
Is it just me? All arrows are black, cant see where to click :(

Great theme otherwise, keep up good work!

**Comment by s10wen** [comment]
What version are you using please?

**Comment by s10wen** [comment]
Fixed in Stable Version 29.0.1547.62

![screen shot 2013-08-30 at 11 21 22](https://f.cloud.github.com/assets/1136114/1056740/2baafa9e-115e-11e3-8e63-ad793e54baed.png)
