### ISSUE TITLE
Chrome changes ?

### ISSUE THREAD

**Issue by antoniobrandao** [s10wen/SO-Dark-Monokai-v3#29]
This stopped worked recently for me. Has Google made changes to Chrome or is it just me?

**Comment by s10wen** [comment]
If you're using Canary please see the README.md

Also please see https://github.com/s10wen/SO-Dark-Monokai-v3/issues/27

**Comment by antoniobrandao** [comment]
I'm using Chrome Version 32.0.1700.102

It was working perfectly until 2 days ago. I'm not sure if my Chrome updated itself recently (don't know how to check) but it was fine before and now everything looks like the default visuals.

I've double-checked the Custom CSS file and it's all there still.

I've also noticed that the paths are not anymore like they are explained in SO-Monokai-v3 front-page. There it is outlined:

Mac:
~/Library/Application\ Support/Google/Chrome/Default/User\ StyleSheets/

which I believe means

/ Chrome / Default User / Stylesheets / Custom.css

but at this moment the path here (mavericks) is:

/ Chrome / Default / User Stylesheets / Custom.css

**Comment by antoniobrandao** [comment]
Btw: I never attempted to install this in Canary

**Comment by s10wen** [comment]
Sorry I've not done much work on this recently, I'm trying to focus on zero-dark-themes https://github.com/s10wen/SO-Dark-Monokai-v3/issues/27

If recommend checking that out, it's much better, if you have trouble getting it up and running please add an issue over on that repo and I'll help you out. Likelihood is I'll stop maintaining this repo and move over to my s10wen-monokai on zero-dark-themes

**Comment by mauricecruz** [comment]
@antoniobrandao in v32.0.1700 the id changed from `#-webkit-web-inspector` to `#-blink-dev-tools`.  That'll fix your issue. 

But yea, if you want continual updates, you'll want to switch over to https://github.com/mauricecruz/zero-base-themes

**Comment by antoniobrandao** [comment]
Thanks a lot for the tip, I really appreciate it.

I don't want to interfere but I would suggest it could be a good idea to
wither update the current SO-Dark-Monokai-v3 or remove it completely?

Because as you can see here
http://devthemez.com/themes/chrome-developer-tools?sort=downloads

Your theme is incredibly popular! (congratulations:) so a lot of people are
now downloading and possibly running into the same problem

Perhaps in zero-base-themes you could have the latest Monokai compilation
being deployed in parallel to the SO-Dark-Monokai-v3 repository?

I'm trying to use zero-base -themes now. If I fail at that I will apply
that tip to the SO-Dark-Monokai-v3's CSS.

Thanks again for the tip, and for the theme, it's the best ;)
