### ISSUE TITLE
Network Tab

### ISSUE THREAD

**Issue by wkerswell** [s10wen/SO-Dark-Monokai-v3#32]
Hi, 
I find it really hard to view the headers in the network tab. Would someone be able to update it or point me in the right direction to fork it? 
![screen shot 2014-11-20 at 14 48 40](https://cloud.githubusercontent.com/assets/3217365/5126368/57433ec0-70c4-11e4-941a-2dfe6f000a48.png)

**Comment by s10wen** [comment]
Hi @wkerswell I'm no longer supporting this repo, it's moved over to https://github.com/mauricecruz/zero-base-themes where I've got my theme running https://github.com/mauricecruz/zero-base-themes/blob/master/themes/s10wen-monokai.less

Please can you try and use this and see if it's still an issue there, if so can you submit an issue there I'll look at improving, cheers.

**Comment by wkerswell** [comment]
Thanks for the quick reply I will check it out. Thanks

**Comment by s10wen** [comment]
@wkerswell no worries, I did a video as well, showing you how to get up and running / create your theme if you want: http://s10wen.com/blog/2014/03/12/chrome-dev-tools-theming-with-zero-base-themes/

**Comment by wkerswell** [comment]
Awesome thank you very much!

**Comment by wkerswell** [comment]
Few things have changed since  the video but it was super helpful thank you very much :)
