### ISSUE TITLE
Looks like image sprites have changed in Version 28.0.1469.0 canary.

### ISSUE THREAD

**Issue by s10wen** [s10wen/SO-Dark-Monokai-v3#8]

**Comment by s10wen** [comment]
cc @addyosmani @paulirish is there any advice you can give to help future proof Chrome Dev Tool theming?

http://feeds.feedburner.com/webinspectorcommits is cool, but there's a lot going on there.

**Comment by paulirish** [comment]
two quick things
1) as of blink, that feed no longer tracks where chrome devtools is going.
https://chromium.googlesource.com/chromium/blink does, though we dont have
a feed yet.
2) can't make promises for our themers. DOM always changes. we'll minimize
it but can't avoid it.

**Comment by s10wen** [comment]
k, ta, is it possible to view all the images available? e.g. chrome-devtools://devtools/Images/statusbarButtonGlyphs.png

**Comment by paulirish** [comment]
https://chromium.googlesource.com/chromium/blink/+/master/Source/WebCore/inspector/front-end/Images/has
a list but they don't show up :p

On Mon, Apr 8, 2013 at 12:25 PM, Simon Owen Design <notifications@github.com

**Comment by s10wen** [comment]
@paulirish not even getting a list, just 404 :frowning:

**Comment by s10wen** [comment]
Think I found them, will get a repo set up with them in :smile:

**Comment by s10wen** [comment]
https://github.com/simonowendesign/chrome-dev-tools-images

**Comment by s10wen** [comment]
Fixed: https://github.com/simonowendesign/SO-Dark-Monokai-v3/commit/f7981b89c24725a3e68b4c6892e39393cd1ef6af
